services:
  mariadb:
    build: ./requirements/Mariadb
    volumes:
      - /home/xhamzall/data/mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    container_name: mariadb
    image: mariadb
    restart: always
  web:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - /home/xhamzall/data/wordpress:/var/www/html
    ports:
      - 443:443
    networks:
      - inception
    image: nginx
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/xhamzall/data/wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
networks:
  inception:
